// Code generated by "callbackgen -type LocalActiveOrderBook"; DO NOT EDIT.

package bbgo

import (
	"github.com/ycdesu/spreaddog/pkg/types"
)

func (b *LocalActiveOrderBook) OnFilled(cb func(o types.Order)) {
	b.filledCallbacks = append(b.filledCallbacks, cb)
}

func (b *LocalActiveOrderBook) EmitFilled(o types.Order) {
	for _, cb := range b.filledCallbacks {
		cb(o)
	}
}
